"""Initial migration with auto-increment integer IDs

Revision ID: 863df106f31d
Revises: 
Create Date: 2024-11-05 10:46:29.956177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '863df106f31d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('short_description', sa.String(length=300), nullable=False),
    sa.Column('questions', sa.JSON(), nullable=True),
    sa.Column('answers', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('videos', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('culinary',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('short_description', sa.String(length=300), nullable=False),
    sa.Column('questions', sa.JSON(), nullable=True),
    sa.Column('answers', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('videos', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('culture',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('short_description', sa.String(length=300), nullable=False),
    sa.Column('questions', sa.JSON(), nullable=True),
    sa.Column('answers', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('videos', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('media_type', sa.String(length=10), nullable=False),
    sa.Column('media_url', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('blog_id', sa.Integer(), nullable=True),
    sa.Column('culinary_id', sa.Integer(), nullable=True),
    sa.Column('culture_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['blog_id'], ['blog.id'], ),
    sa.ForeignKeyConstraint(['culinary_id'], ['culinary.id'], ),
    sa.ForeignKeyConstraint(['culture_id'], ['culture.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media')
    op.drop_table('culture')
    op.drop_table('culinary')
    op.drop_table('blog')
    # ### end Alembic commands ###
